In [1]:
# libraries for EDA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#To display the plots
%matplotlib inline

# scikit learn library for machine learning algorithms, data preprocessing, and evaluation
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OrdinalEncoder, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_validate, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import classification_report, confusion_matrix, log_loss, recall_score, accuracy_score, precision_score, f1_score, roc_auc_score
from sklearn.metrics import make_scorer, average_precision_score, PrecisionRecallDisplay, precision_recall_curve, roc_curve
from sklearn.metrics import ConfusionMatrixDisplay

from sklearn.compose import make_column_transformer, ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, PowerTransformer
from sklearn.pipeline import Pipeline

import scikitplot as skplt

# yellowbrick library for visualizing the model performance
from yellowbrick.classifier import ConfusionMatrix, PrecisionRecallCurve
from yellowbrick.classifier import PrecisionRecallCurve
from sklearn.pipeline import Pipeline

# to get rid of the warnings
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

plt.rcParams["figure.figsize"] = (10,6)
sns.set_style("whitegrid", {'axes.grid' : True})

# To display maximum columns
pd.set_option('display.max_columns', 50)

# To display maximum rows
pd.set_option('display.max_rows', 50)

# To set float format
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
def eval_metric(model, X_train, y_train, X_test, y_test):   
    y_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)
    
    print("Test_Set")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()
    print("Train_Set")
    print(confusion_matrix(y_train, y_train_pred))
    print(classification_report(y_train, y_train_pred))

In [30]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test_x.csv')

df = train.copy()

In [31]:
df['A'] = df['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] / df['Yıllık Ortalama Sepete Atılan Ürün Adedi']
df['B'] = df['Yıllık Ortalama Satın Alım Miktarı'] / df['Yıllık Ortalama Gelir'] 
df['C'] = df['Yıllık Ortalama Satın Alım Miktarı'] / df['Yıllık Ortalama Sipariş Verilen Ürün Adedi']

In [32]:
test['A'] = test['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] / test['Yıllık Ortalama Sepete Atılan Ürün Adedi'] 
test['B'] = test['Yıllık Ortalama Satın Alım Miktarı'] / test['Yıllık Ortalama Gelir']
test['C'] = test['Yıllık Ortalama Satın Alım Miktarı'] / test['Yıllık Ortalama Sipariş Verilen Ürün Adedi']

In [47]:
df.describe().T.style.background_gradient(axis=1, cmap="Spectral")

In [33]:
from sklearn.model_selection import train_test_split

X = df.drop(["Öbek İsmi", 'index'], axis=1)

y = df["Öbek İsmi"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, stratify=y)

In [34]:
cat = X_train.select_dtypes("object").columns
cat

Index(['Cinsiyet', 'Yaş Grubu', 'Medeni Durum', 'Eğitim Düzeyi',
       'İstihdam Durumu', 'Yaşadığı Şehir', 'En Çok İlgilendiği Ürün Grubu',
       'Eğitime Devam Etme Durumu'],
      dtype='object')

In [35]:
ord_enc = OrdinalEncoder(handle_unknown='use_encoded_value', 
                         unknown_value=-1)

column_trans = make_column_transformer((ord_enc, cat), 
                                        remainder='passthrough')

In [36]:
import lightgbm as lgb

operations_lightgbm = [("OrdinalEncoder", column_trans), 
                       ("lightgbm_model", lgb.LGBMClassifier())]

lightgbm_model = Pipeline(steps=operations_lightgbm)

lightgbm_model.fit(X_train, y_train)

Pipeline(steps=[('OrdinalEncoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinalencoder',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  Index(['Cinsiyet', 'Yaş Grubu', 'Medeni Durum', 'Eğitim Düzeyi',
       'İstihdam Durumu', 'Yaşadığı Şehir', 'En Çok İlgilendiği Ürün Grubu',
       'Eğitime Devam Etme Durumu'],
      dtype='object'))])),
                ('lightgbm_model', LGBMClassifier())])

In [37]:
eval_metric(lightgbm_model, X_train, y_train, X_test, y_test)

Test_Set
[[ 96   1   2   1   0   2   1   1]
 [  1  80   0   0   0   1   0   0]
 [  0   0  97   0   0   4   1   2]
 [  1   0   1  99   3   0   1   3]
 [  1   0   0   1 104   0   0   0]
 [  1   0   0   2   0  97   2   1]
 [  0   1   1   0   0   0 101   1]
 [  1   0   1   2   0   1   0 103]]
              precision    recall  f1-score   support

      obek_1       0.95      0.92      0.94       104
      obek_2       0.98      0.98      0.98        82
      obek_3       0.95      0.93      0.94       104
      obek_4       0.94      0.92      0.93       108
      obek_5       0.97      0.98      0.98       106
      obek_6       0.92      0.94      0.93       103
      obek_7       0.95      0.97      0.96       104
      obek_8       0.93      0.95      0.94       108

    accuracy                           0.95       819
   macro avg       0.95      0.95      0.95       819
weighted avg       0.95      0.95      0.95       819


Train_Set
[[588   0   0   0   0   0   0   0]
 [  0 465   0

In [26]:
from sklearn.metrics import accuracy_score

y_pred = lightgbm_model.predict(X_test)
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

LightGBM Model accuracy score: 0.9548


In [42]:
import lightgbm as lgb

operations_lightgbm = [("OrdinalEncoder", column_trans), 
                       ("lightgbm_model", lgb.LGBMClassifier(boosting_type='dart',
                                                             colsample_bytree=0.6,
                                                             is_unbalance=True,
                                                             learning_rate=0.01,
                                                             min_child_samples=30,
                                                             n_estimators=1000,
                                                             num_leaves=70,
                                                             reg_alpha=0,
                                                             scale_pos_weight=4,
                                                             subsample_for_bin=3000))]

lightgbm_model = Pipeline(steps=operations_lightgbm)

lightgbm_model.fit(X_train, y_train)

Pipeline(steps=[('OrdinalEncoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinalencoder',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  Index(['Cinsiyet', 'Yaş Grubu', 'Medeni Durum', 'Eğitim Düzeyi',
       'İstihdam Durumu', 'Yaşadığı Şehir', 'En Çok İlgilendiği Ürün Grubu',
       'Eğitime Devam Etme Durumu'],
      dtype='object'))])),
                ('lightgbm_model',
                 LGBMClassifier(boosting_type='dart', colsample_bytree=0.6,
                                is_unbalance=True, learning_rate=0.01,
                                min_child_samples=30, n_estimators=1000,
                                num_leaves=70, reg_alpha=0, scale_pos_weight=4,
                                subsample_for_bin=3000))])

In [43]:
eval_metric(lightgbm_model, X_train, y_train, X_test, y_test)

Test_Set
[[ 97   1   1   1   0   2   1   1]
 [  1  80   0   0   0   1   0   0]
 [  0   0  97   0   0   4   1   2]
 [  1   0   1  99   3   0   1   3]
 [  1   0   0   1 104   0   0   0]
 [  1   0   0   2   0  97   2   1]
 [  0   1   1   0   0   0 101   1]
 [  1   0   1   1   0   1   1 103]]
              precision    recall  f1-score   support

      obek_1       0.95      0.93      0.94       104
      obek_2       0.98      0.98      0.98        82
      obek_3       0.96      0.93      0.95       104
      obek_4       0.95      0.92      0.93       108
      obek_5       0.97      0.98      0.98       106
      obek_6       0.92      0.94      0.93       103
      obek_7       0.94      0.97      0.96       104
      obek_8       0.93      0.95      0.94       108

    accuracy                           0.95       819
   macro avg       0.95      0.95      0.95       819
weighted avg       0.95      0.95      0.95       819


Train_Set
[[585   0   1   0   0   1   1   0]
 [  1 464   0

In [29]:
from sklearn.metrics import accuracy_score

y_pred = lightgbm_model.predict(X_test)
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

LightGBM Model accuracy score: 0.9548


In [84]:
predict = lightgbm_model.predict(test)

In [85]:
data = {
    'id': range(2340),
    'Öbek İsmi': predict
}
sub_df = pd.DataFrame(data)
sub_df.set_index('id', inplace=True)
sub_df

Öbek İsmi
id            
0       obek_3
1       obek_3
2       obek_2
3       obek_6
4       obek_1
...        ...
2335    obek_8
2336    obek_2
2337    obek_7
2338    obek_5
2339    obek_6

[2340 rows x 1 columns]

In [86]:
sub_df.to_csv('submission_lgbm_fe6.csv')

In [73]:
import optuna

def objective(trial):
    # LightGBM için hiperparametre aralıklarını belirleme
    params = {
        'objective': 'multiclass',  # Sınıflandırma olduğu için 'binary' olarak ayarlandı
        'boosting_type': 'gbdt',
        'num_leaves': trial.suggest_int('num_leaves', 10, 100),
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.1),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0),
    }
    
    operations_lightgbm = [("OrdinalEncoder", column_trans), 
                           ("lightgbm_model", lgb.LGBMClassifier(**params))]

    lightgbm_model = Pipeline(steps=operations_lightgbm)
    # LightGBM modelini oluşturma
    # model = lgb.LGBMClassifier(**params)
    # Modeli veri ile eğitme
    lightgbm_model.fit(X_train, y_train)
    # Doğrulama verisi üzerinde modelin performansını hesaplama (örneğin doğruluk)
    accuracy = lightgbm_model.score(X_test, y_test)
    return accuracy  # Amac fonksiyonu, maximize edilmeye çalışılan değeri döndürmelidir

In [74]:
study = optuna.create_study(direction='maximize')  # Doğruluğu maximize etmeye çalıştığımız için 'maximize'
study.optimize(objective, n_trials=100)  # 100 deneme yaparak hiperparametre optimizasyonu gerçekleştirme

[I 2023-08-24 21:29:55,044] A new study created in memory with name: no-name-64e952ab-9830-4705-bcf5-b560f7311cb1
[I 2023-08-24 21:29:55,438] Trial 0 finished with value: 0.9560439560439561 and parameters: {'num_leaves': 33, 'learning_rate': 0.021406601638270958, 'feature_fraction': 0.9064070445205542}. Best is trial 0 with value: 0.9560439560439561.


[LightGBM] [Warning] feature_fraction is set=0.5686044281958337, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5686044281958337


[I 2023-08-24 21:29:56,298] Trial 1 finished with value: 0.9560439560439561 and parameters: {'num_leaves': 74, 'learning_rate': 0.007201565396984265, 'feature_fraction': 0.5686044281958337}. Best is trial 0 with value: 0.9560439560439561.


[LightGBM] [Warning] feature_fraction is set=0.5959831281472725, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5959831281472725


[I 2023-08-24 21:29:57,098] Trial 2 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 63, 'learning_rate': 0.05357009914065205, 'feature_fraction': 0.5959831281472725}. Best is trial 2 with value: 0.9578754578754579.


[LightGBM] [Warning] feature_fraction is set=0.8219083960116862, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8219083960116862


[I 2023-08-24 21:29:57,367] Trial 3 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 12, 'learning_rate': 0.028065943472511717, 'feature_fraction': 0.8219083960116862}. Best is trial 2 with value: 0.9578754578754579.


[LightGBM] [Warning] feature_fraction is set=0.7777079354304326, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7777079354304326


[I 2023-08-24 21:29:57,665] Trial 4 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 20, 'learning_rate': 0.09566219634591548, 'feature_fraction': 0.7777079354304326}. Best is trial 2 with value: 0.9578754578754579.


[LightGBM] [Warning] feature_fraction is set=0.5272523507226217, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5272523507226217


[I 2023-08-24 21:29:58,078] Trial 5 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 38, 'learning_rate': 0.04344729836905109, 'feature_fraction': 0.5272523507226217}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9867672549559214, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9867672549559214


[I 2023-08-24 21:29:58,609] Trial 6 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 44, 'learning_rate': 0.09754917952787263, 'feature_fraction': 0.9867672549559214}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.37408205108197745, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.37408205108197745


[I 2023-08-24 21:29:58,891] Trial 7 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 24, 'learning_rate': 0.08202034074166996, 'feature_fraction': 0.37408205108197745}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.7081502968796003, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7081502968796003


[I 2023-08-24 21:29:59,304] Trial 8 finished with value: 0.9560439560439561 and parameters: {'num_leaves': 36, 'learning_rate': 0.01447771311545893, 'feature_fraction': 0.7081502968796003}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.2807795289830015, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2807795289830015


[I 2023-08-24 21:29:59,834] Trial 9 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 57, 'learning_rate': 0.06690944806656615, 'feature_fraction': 0.2807795289830015}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.10482858132830714, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.10482858132830714


[I 2023-08-24 21:30:00,459] Trial 10 finished with value: 0.9542124542124543 and parameters: {'num_leaves': 94, 'learning_rate': 0.039993354433946415, 'feature_fraction': 0.10482858132830714}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9883517172042662, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9883517172042662


[I 2023-08-24 21:30:01,114] Trial 11 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 44, 'learning_rate': 0.05961961842758947, 'feature_fraction': 0.9883517172042662}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9891112377623064, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9891112377623064


[I 2023-08-24 21:30:01,805] Trial 12 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 51, 'learning_rate': 0.09819292135638086, 'feature_fraction': 0.9891112377623064}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6770119443769701, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6770119443769701


[I 2023-08-24 21:30:02,532] Trial 13 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 72, 'learning_rate': 0.03921932297121144, 'feature_fraction': 0.6770119443769701}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.44826393713610735, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.44826393713610735


[I 2023-08-24 21:30:02,960] Trial 14 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 37, 'learning_rate': 0.07136456089286564, 'feature_fraction': 0.44826393713610735}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8371698440149893, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8371698440149893


[I 2023-08-24 21:30:03,528] Trial 15 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 48, 'learning_rate': 0.04636990934756844, 'feature_fraction': 0.8371698440149893}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6776944723221654, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6776944723221654


[I 2023-08-24 21:30:03,890] Trial 16 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 27, 'learning_rate': 0.07971937589917977, 'feature_fraction': 0.6776944723221654}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4969038923762157, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4969038923762157


[I 2023-08-24 21:30:04,782] Trial 17 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 100, 'learning_rate': 0.057078138634352425, 'feature_fraction': 0.4969038923762157}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5868211538686188, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5868211538686188


[I 2023-08-24 21:30:05,486] Trial 18 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 63, 'learning_rate': 0.03201330563174348, 'feature_fraction': 0.5868211538686188}. Best is trial 5 with value: 0.9587912087912088.
[I 2023-08-24 21:30:05,679] Trial 19 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 10, 'learning_rate': 0.04787571117135377, 'feature_fraction': 0.8792254060127097}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8792254060127097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8792254060127097
[LightGBM] [Warning] feature_fraction is set=0.7100871295687918, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7100871295687918


[I 2023-08-24 21:30:06,172] Trial 20 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 43, 'learning_rate': 0.0874952884330743, 'feature_fraction': 0.7100871295687918}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4068157816579492, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4068157816579492


[I 2023-08-24 21:30:06,493] Trial 21 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 24, 'learning_rate': 0.08405118917965404, 'feature_fraction': 0.4068157816579492}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.3724196643779151, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3724196643779151


[I 2023-08-24 21:30:06,837] Trial 22 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 29, 'learning_rate': 0.09286592621986849, 'feature_fraction': 0.3724196643779151}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5051960967696711, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5051960967696711


[I 2023-08-24 21:30:07,299] Trial 23 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 39, 'learning_rate': 0.07802805913003605, 'feature_fraction': 0.5051960967696711}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.36961167782757987, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.36961167782757987


[I 2023-08-24 21:30:07,622] Trial 24 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 18, 'learning_rate': 0.09998621993739151, 'feature_fraction': 0.36961167782757987}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.2852764316881247, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2852764316881247


[I 2023-08-24 21:30:08,271] Trial 25 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 52, 'learning_rate': 0.09028761299892368, 'feature_fraction': 0.2852764316881247}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6280888379632331, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6280888379632331


[I 2023-08-24 21:30:08,565] Trial 26 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 19, 'learning_rate': 0.06566139866259374, 'feature_fraction': 0.6280888379632331}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5263538734107548, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5263538734107548


[I 2023-08-24 21:30:08,986] Trial 27 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 33, 'learning_rate': 0.08301955133714933, 'feature_fraction': 0.5263538734107548}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.7572455127657203, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7572455127657203


[I 2023-08-24 21:30:09,392] Trial 28 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 29, 'learning_rate': 0.07655551813011777, 'feature_fraction': 0.7572455127657203}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9548689312507662, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9548689312507662


[I 2023-08-24 21:30:10,045] Trial 29 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 44, 'learning_rate': 0.09178785873682181, 'feature_fraction': 0.9548689312507662}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9148567972989275, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9148567972989275


[I 2023-08-24 21:30:10,810] Trial 30 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 59, 'learning_rate': 0.08731476453665002, 'feature_fraction': 0.9148567972989275}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.2536642789969298, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2536642789969298


[I 2023-08-24 21:30:11,348] Trial 31 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 56, 'learning_rate': 0.07055914374947533, 'feature_fraction': 0.2536642789969298}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5560385793402869, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5560385793402869


[I 2023-08-24 21:30:12,188] Trial 32 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 74, 'learning_rate': 0.061973782258753725, 'feature_fraction': 0.5560385793402869}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4612135925449593, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4612135925449593


[I 2023-08-24 21:30:12,989] Trial 33 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 63, 'learning_rate': 0.0717636019417545, 'feature_fraction': 0.4612135925449593}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6403925290914312, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6403925290914312


[I 2023-08-24 21:30:13,790] Trial 34 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 68, 'learning_rate': 0.06426985196500451, 'feature_fraction': 0.6403925290914312}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6056649761492063, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6056649761492063


[I 2023-08-24 21:30:14,192] Trial 35 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 33, 'learning_rate': 0.053502278510428096, 'feature_fraction': 0.6056649761492063}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5271759606284738, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5271759606284738


[I 2023-08-24 21:30:15,140] Trial 36 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 81, 'learning_rate': 0.09474485994435197, 'feature_fraction': 0.5271759606284738}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8190730412987339, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8190730412987339


[I 2023-08-24 21:30:15,635] Trial 37 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 40, 'learning_rate': 0.08445157534527432, 'feature_fraction': 0.8190730412987339}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.30948372871728913, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.30948372871728913


[I 2023-08-24 21:30:16,279] Trial 38 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 49, 'learning_rate': 0.07624597721706539, 'feature_fraction': 0.30948372871728913}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.2143785914525001, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2143785914525001


[I 2023-08-24 21:30:16,941] Trial 39 finished with value: 0.9560439560439561 and parameters: {'num_leaves': 84, 'learning_rate': 0.019175210514426187, 'feature_fraction': 0.2143785914525001}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5671077092415676, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5671077092415676


[I 2023-08-24 21:30:17,547] Trial 40 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 58, 'learning_rate': 0.09998275220995391, 'feature_fraction': 0.5671077092415676}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9501649301780812, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9501649301780812


[I 2023-08-24 21:30:18,078] Trial 41 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 46, 'learning_rate': 0.06086984055016315, 'feature_fraction': 0.9501649301780812}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.996728418880387, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.996728418880387


[I 2023-08-24 21:30:18,595] Trial 42 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 42, 'learning_rate': 0.056840875066272153, 'feature_fraction': 0.996728418880387}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8933665031052087, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8933665031052087


[I 2023-08-24 21:30:19,047] Trial 43 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 36, 'learning_rate': 0.06903825810153971, 'feature_fraction': 0.8933665031052087}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8628052786598337, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8628052786598337


[I 2023-08-24 21:30:19,677] Trial 44 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 53, 'learning_rate': 0.05053815606405067, 'feature_fraction': 0.8628052786598337}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.934590058327358, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.934590058327358


[I 2023-08-24 21:30:20,037] Trial 45 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 23, 'learning_rate': 0.05830287822996504, 'feature_fraction': 0.934590058327358}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9676943705061771, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9676943705061771


[I 2023-08-24 21:30:20,361] Trial 46 finished with value: 0.956959706959707 and parameters: {'num_leaves': 16, 'learning_rate': 0.04435583311499001, 'feature_fraction': 0.9676943705061771}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.7846382980984805, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7846382980984805


[I 2023-08-24 21:30:20,667] Trial 47 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 14, 'learning_rate': 0.06694698564292942, 'feature_fraction': 0.7846382980984805}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9058181097500677, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9058181097500677


[I 2023-08-24 21:30:21,331] Trial 48 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 48, 'learning_rate': 0.07368912936049737, 'feature_fraction': 0.9058181097500677}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4696243767728364, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4696243767728364


[I 2023-08-24 21:30:21,729] Trial 49 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 24, 'learning_rate': 0.08144538936778264, 'feature_fraction': 0.4696243767728364}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9823988480573971, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9823988480573971


[I 2023-08-24 21:30:22,532] Trial 50 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 66, 'learning_rate': 0.09585677117884034, 'feature_fraction': 0.9823988480573971}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9911277065010623, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9911277065010623


[I 2023-08-24 21:30:23,170] Trial 51 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 50, 'learning_rate': 0.08956837081778056, 'feature_fraction': 0.9911277065010623}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9187836695024494, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9187836695024494


[I 2023-08-24 21:30:23,834] Trial 52 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 54, 'learning_rate': 0.08485144924325895, 'feature_fraction': 0.9187836695024494}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8609766519569684, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8609766519569684


[I 2023-08-24 21:30:24,295] Trial 53 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 33, 'learning_rate': 0.07763705823054794, 'feature_fraction': 0.8609766519569684}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9983315490949324, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9983315490949324


[I 2023-08-24 21:30:24,882] Trial 54 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 45, 'learning_rate': 0.09517056194256773, 'feature_fraction': 0.9983315490949324}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9461257566660771, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9461257566660771


[I 2023-08-24 21:30:25,565] Trial 55 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 60, 'learning_rate': 0.09022329070659704, 'feature_fraction': 0.9461257566660771}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4036282395501259, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4036282395501259


[I 2023-08-24 21:30:25,997] Trial 56 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 39, 'learning_rate': 0.08188602712330431, 'feature_fraction': 0.4036282395501259}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8872076182209009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8872076182209009


[I 2023-08-24 21:30:26,392] Trial 57 finished with value: 0.956959706959707 and parameters: {'num_leaves': 28, 'learning_rate': 0.08789708611495298, 'feature_fraction': 0.8872076182209009}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.733000009398333, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.733000009398333


[I 2023-08-24 21:30:26,867] Trial 58 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 42, 'learning_rate': 0.03656665792011544, 'feature_fraction': 0.733000009398333}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8324984791648529, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8324984791648529


[I 2023-08-24 21:30:27,440] Trial 59 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 50, 'learning_rate': 0.07459467543827564, 'feature_fraction': 0.8324984791648529}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9229765735915507, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9229765735915507


[I 2023-08-24 21:30:27,978] Trial 60 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 36, 'learning_rate': 0.08010578685601716, 'feature_fraction': 0.9229765735915507}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6961797919197252, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6961797919197252


[I 2023-08-24 21:30:28,979] Trial 61 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 76, 'learning_rate': 0.043077906947834095, 'feature_fraction': 0.6961797919197252}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6502105123732735, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6502105123732735


[I 2023-08-24 21:30:29,892] Trial 62 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 70, 'learning_rate': 0.03623259693449635, 'feature_fraction': 0.6502105123732735}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.963718173613376, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.963718173613376


[I 2023-08-24 21:30:30,634] Trial 63 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 57, 'learning_rate': 0.049668672363208995, 'feature_fraction': 0.963718173613376}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.796024354947219, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.796024354947219


[I 2023-08-24 21:30:31,235] Trial 64 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 52, 'learning_rate': 0.09262414170226392, 'feature_fraction': 0.796024354947219}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.596593794923325, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.596593794923325


[I 2023-08-24 21:30:31,729] Trial 65 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 46, 'learning_rate': 0.029626976488935884, 'feature_fraction': 0.596593794923325}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5384931536945975, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5384931536945975


[I 2023-08-24 21:30:32,516] Trial 66 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 89, 'learning_rate': 0.09855410201765083, 'feature_fraction': 0.5384931536945975}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.48607385162859146, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48607385162859146


[I 2023-08-24 21:30:33,005] Trial 67 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 32, 'learning_rate': 0.08626237135446763, 'feature_fraction': 0.48607385162859146}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.7533257691536325, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7533257691536325


[I 2023-08-24 21:30:33,651] Trial 68 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 60, 'learning_rate': 0.06755253315957246, 'feature_fraction': 0.7533257691536325}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8672239695873317, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8672239695873317


[I 2023-08-24 21:30:34,569] Trial 69 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 100, 'learning_rate': 0.09700569319476399, 'feature_fraction': 0.8672239695873317}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9430337004401317, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9430337004401317


[I 2023-08-24 21:30:35,252] Trial 70 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 64, 'learning_rate': 0.09136154352701936, 'feature_fraction': 0.9430337004401317}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.448110481626313, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.448110481626313


[I 2023-08-24 21:30:35,707] Trial 71 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 41, 'learning_rate': 0.06315238858626186, 'feature_fraction': 0.448110481626313}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.49848477709452305, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.49848477709452305


[I 2023-08-24 21:30:36,138] Trial 72 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 36, 'learning_rate': 0.07305438170574047, 'feature_fraction': 0.49848477709452305}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5702986460649997, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5702986460649997


[I 2023-08-24 21:30:36,636] Trial 73 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 31, 'learning_rate': 0.06547782822117565, 'feature_fraction': 0.5702986460649997}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6663488753030777, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6663488753030777


[I 2023-08-24 21:30:37,101] Trial 74 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 39, 'learning_rate': 0.07229190945727394, 'feature_fraction': 0.6663488753030777}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9728925873560846, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9728925873560846


[I 2023-08-24 21:30:37,590] Trial 75 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 36, 'learning_rate': 0.06995458646787057, 'feature_fraction': 0.9728925873560846}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.6159622271681129, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6159622271681129


[I 2023-08-24 21:30:37,961] Trial 76 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 25, 'learning_rate': 0.07961341134375421, 'feature_fraction': 0.6159622271681129}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.34446264864606946, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.34446264864606946


[I 2023-08-24 21:30:38,456] Trial 77 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 43, 'learning_rate': 0.09341780722073498, 'feature_fraction': 0.34446264864606946}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.43152224245046855, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.43152224245046855


[I 2023-08-24 21:30:38,958] Trial 78 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 48, 'learning_rate': 0.06005744369323535, 'feature_fraction': 0.43152224245046855}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5157827436204948, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5157827436204948


[I 2023-08-24 21:30:39,273] Trial 79 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 21, 'learning_rate': 0.054738142171736184, 'feature_fraction': 0.5157827436204948}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.89945653168756, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.89945653168756


[I 2023-08-24 21:30:40,024] Trial 80 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 76, 'learning_rate': 0.09744706328066723, 'feature_fraction': 0.89945653168756}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9659469137840487, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9659469137840487


[I 2023-08-24 21:30:40,584] Trial 81 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 46, 'learning_rate': 0.06410407325350326, 'feature_fraction': 0.9659469137840487}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9291293375118281, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9291293375118281


[I 2023-08-24 21:30:41,189] Trial 82 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 55, 'learning_rate': 0.04612810091870388, 'feature_fraction': 0.9291293375118281}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9953340872187233, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9953340872187233


[I 2023-08-24 21:30:41,670] Trial 83 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 38, 'learning_rate': 0.05163133492334744, 'feature_fraction': 0.9953340872187233}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8255724205065628, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8255724205065628


[I 2023-08-24 21:30:42,265] Trial 84 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 51, 'learning_rate': 0.06934209874002925, 'feature_fraction': 0.8255724205065628}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9353381736890516, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9353381736890516


[I 2023-08-24 21:30:42,920] Trial 85 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 44, 'learning_rate': 0.04709311753830177, 'feature_fraction': 0.9353381736890516}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9029660436605494, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9029660436605494


[I 2023-08-24 21:30:44,217] Trial 86 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 96, 'learning_rate': 0.07632816591888923, 'feature_fraction': 0.9029660436605494}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9607186314507153, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9607186314507153


[I 2023-08-24 21:30:45,363] Trial 87 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 70, 'learning_rate': 0.08358095144362981, 'feature_fraction': 0.9607186314507153}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9802903290848866, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9802903290848866


[I 2023-08-24 21:30:45,982] Trial 88 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 48, 'learning_rate': 0.05985973988894106, 'feature_fraction': 0.9802903290848866}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8453865458920687, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8453865458920687


[I 2023-08-24 21:30:46,591] Trial 89 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 54, 'learning_rate': 0.09968219775190194, 'feature_fraction': 0.8453865458920687}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8753048270091603, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8753048270091603


[I 2023-08-24 21:30:46,839] Trial 90 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 12, 'learning_rate': 0.042541361546122855, 'feature_fraction': 0.8753048270091603}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.542304539066126, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.542304539066126


[I 2023-08-24 21:30:47,334] Trial 91 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 41, 'learning_rate': 0.06215177887470591, 'feature_fraction': 0.542304539066126}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5097610750675112, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5097610750675112


[I 2023-08-24 21:30:48,313] Trial 92 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 86, 'learning_rate': 0.04889531657214535, 'feature_fraction': 0.5097610750675112}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.478300919946516, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.478300919946516


[I 2023-08-24 21:30:49,517] Trial 93 finished with value: 0.9578754578754579 and parameters: {'num_leaves': 91, 'learning_rate': 0.05359220901833936, 'feature_fraction': 0.478300919946516}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.8031524993265308, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8031524993265308


[I 2023-08-24 21:30:50,054] Trial 94 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 47, 'learning_rate': 0.05728880971512183, 'feature_fraction': 0.8031524993265308}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.4058688665866419, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4058688665866419


[I 2023-08-24 21:30:50,450] Trial 95 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 30, 'learning_rate': 0.05540201915446944, 'feature_fraction': 0.4058688665866419}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9181696808418898, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9181696808418898


[I 2023-08-24 21:30:50,915] Trial 96 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 34, 'learning_rate': 0.05205105530138971, 'feature_fraction': 0.9181696808418898}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.579885827912308, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.579885827912308


[I 2023-08-24 21:30:51,448] Trial 97 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 44, 'learning_rate': 0.06638294282792234, 'feature_fraction': 0.579885827912308}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.5597608048095633, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5597608048095633


[I 2023-08-24 21:30:52,219] Trial 98 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 79, 'learning_rate': 0.09461942365021009, 'feature_fraction': 0.5597608048095633}. Best is trial 5 with value: 0.9587912087912088.


[LightGBM] [Warning] feature_fraction is set=0.9988582570546629, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9988582570546629


[I 2023-08-24 21:30:53,023] Trial 99 finished with value: 0.9587912087912088 and parameters: {'num_leaves': 61, 'learning_rate': 0.08674991106010442, 'feature_fraction': 0.9988582570546629}. Best is trial 5 with value: 0.9587912087912088.


In [75]:
print('En iyi sonuç (doğruluk): ', study.best_value)
print('En iyi hiperparametreler: ', study.best_params)

En iyi sonuç (doğruluk):  0.9587912087912088
En iyi hiperparametreler:  {'num_leaves': 38, 'learning_rate': 0.04344729836905109, 'feature_fraction': 0.5272523507226217}
